server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cloud8001_routh            #路由id，建议配合服务名
          #uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://CLOUD-SERVICE
          predicates:
            - Path=/hystrix/staff_OK/**  #断言，路径相匹配的进行路由
        - id: cloud8001_routh1
          uri: lb://CLOUD-SERVICE
          predicates:
            - Path=/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka.7001.com:7001/eureka/