server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lianxi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka/
  instance:
    instance-id: cloud8001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.zhangxun.cloud.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl